POST   http://localhost:5000/users/login
Content-Type: application/json

{
    
    "name": "Rafal",
    "password" : "xylo"
    

}
###

POST http://localhost:4000/users/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiaHVudGVyIiwiaWF0IjoxNjk4MDc0NDExLCJleHAiOjE2OTgwNzUwMTF9.aXQiNXrfaztTZZ3GNDcUdh5FRVsJNvrq6wfXyAMmr2M
###
POST http://localhost:5000/users/token 
Content-Type: application/json

{
    "token" : "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiaHVudGVyIiwiaWF0IjoxNjk3OTA3MjE1fQ.bB6maeddaSuDH1recDP6yF4I1Avan-jY3fgivgAMMBA"
}

###

DELETE  http://localhost:5000/users/logOut
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiaHVudGVyIiwiaWF0IjoxNjk3OTA3MjY2LCJleHAiOjE2OTc5MDczMjZ9.bG3oiv-yI5OuWKS0SXdHOWEntM9uW49SzCwD1o0K4OI"
}

###

POST http://localhost:5000/users/trans
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiUmFmYcWCIiwiaWF0IjoxNjk4MjU3MzE0LCJleHAiOjE2OTgyNTc5MTR9.lro5cYmYQjJziYhUynszdQ_F_exc-h6KPSW02of0TLw
Content-Type: application/json

{
  "type" : "Sell",
  "from" : "pln",
  "to"   : "euro",
  "buy"  : 343,
  "sell" : 200,
  "course" : 3

}



###

POST  http://localhost:5000/users/newUser
Content-Type: application/json

{
    "name" : "Rafal",
    "password" : "xylo",
    "wallet":0,
    "email" : "text@.com",
    "phoneNumber": 156369874,
    "accountNumber": "15639874569852365874",
    "pin":3453,
    "currencyCode" :"euro",
    "currency" : [{"currencyCode":"pln","amount":0}],
    "currencyaccount":"15639874569565465465874"
}

####

POST  http://localhost:5000/users/mainAccount
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiUmFmYcWCIiwiaWF0IjoxNjk4MTc4MzQxLCJleHAiOjE2OTgxNzg5NDF9.0p8KcCRzg-bXM1Q7tLD_SWHOb3YIuHMDC08cpCkvUwo
Content-Type: application/json

{
  
    "amount":160

}

####

PUT  http://localhost:5000/users/updateCurrency
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiUmFmYcWCIiwiaWF0IjoxNjk4MTc2OTY3LCJleHAiOjE2OTgxNzc1Njd9.3db81qMsz-wVl1Xl8FA5wA-qdYL5eIPd3_-XdWGWohY
Content-Type: application/json



  
[
  {
    "amount": 3770,
    "currencyCode": "pln"
  },
   {
    "amount": 3770,
    "currencyCode": "funt"
  }
]

####
GET   http://localhost:5000/users/getCurrency
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiUmFmYcWCIiwiaWF0IjoxNjk4MTc2NDA4LCJleHAiOjE2OTgxNzcwMDh9.ahAZ9LVlJUg3ANdlefiG8XhYiHJYstblRBZUVoo0jXw


####
GET   http://localhost:5000/users/getTransations
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiUmFmYcWCIiwiaWF0IjoxNjk4MjU2ODQxLCJleHAiOjE2OTgyNTc0NDF9.4YLXOsMO-iKdZXfFX04Q3_UaHTiskm8pgVyWNKhjUFw


####
DELETE    http://localhost:5000/users/deleteUser
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiUmFmYcWCIiwiaWF0IjoxNjk4MTc3OTA3LCJleHAiOjE2OTgxNzg1MDd9.Hqpi2kTlUKlh_xHnDtuJDqRL1TFuARl3q15vC6ZcVno

  

####
GET     http://localhost:5000/users/get

